CREATE TABLE emp(
	empno NUMBER(4) CONSTRAINT emp_pk PRIMARY KEY,
	ename VARCHAR2(10) CONSTRAINT en_chk CHECK(ename=UPPER(ename)),
	job VARCHAR2(10),
	mgrno NUMBER(4) CONSTRAINT mno_fk REFERENCES emp(empno),
	hiredate DATE DEFAULT SYSDATE,
	sal NUMBER(7,2) CONSTRAINT sal_nm NOT NULL,
	comm NUMBER(7,2),
	deptno NUMBER(4) CONSTRAINT dept_nm NOT NULL,
	CONSTRAINT emp_dept FOREIGN KEY(deptno) REFERENCES dept(deptno) ON DELETE CASCADE);

DESC emp;
